# Generated by Django 4.0.4 on 2022-04-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_sector', max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='client',
            name='data_package',
            field=models.CharField(choices=[('2GB', ' 2Gb'), ('5GB', ' 5Gb'), ('10GB', ' 10Gb'), ('50GB', ' 50Gb'), ('100GB', ' 100Gb')], default='2GB', max_length=5),
        ),
    ]
