# Generated by Django 4.0.4 on 2022-04-29 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_sectors_rename_name_client_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_size', models.CharField(choices=[('2GB', ' 2Gb'), ('5GB', ' 5Gb'), ('10GB', ' 10Gb'), ('50GB', ' 50Gb'), ('100GB', ' 100Gb')], default='2GB', max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='sectors',
            field=models.ManyToManyField(to='client.sectors'),
        ),
        migrations.AlterField(
            model_name='client',
            name='data_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.datapackage'),
        ),
    ]
