# Generated by Django 4.0.4 on 2022-04-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_datapackage_client_sectors_alter_client_data_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sectors',
            field=models.ManyToManyField(related_name='sectors', to='client.sectors'),
        ),
        migrations.AlterField(
            model_name='datapackage',
            name='package_size',
            field=models.CharField(choices=[('2GB', '2GB'), ('5GB', '5GB'), ('10GB', '10GB'), ('50GB', '50GB'), ('100GB', '100GB')], max_length=5, null=True),
        ),
    ]
