# Generated by Django 4.0.4 on 2022-04-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_sectors_alter_datapackage_package_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='data_package',
        ),
        migrations.AddField(
            model_name='client',
            name='package',
            field=models.CharField(choices=[('2GB', '2GB'), ('5GB', '5GB'), ('10GB', '10GB'), ('50GB', '50GB'), ('100GB', '100GB')], max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='DataPackage',
        ),
    ]
