# Generated by Django 4.0.4 on 2022-04-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_client_data_package_client_package_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='package',
            new_name='data_package',
        ),
    ]
