# Generated by Django 4.0.4 on 2022-05-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_rename_package_client_data_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sectors',
            field=models.ManyToManyField(default=None, related_name='sectors', to='client.sectors'),
        ),
    ]
