# Generated by Django 4.0.4 on 2022-05-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_client_sectors'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
    ]
